# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.19.5
# Mod Properties
mod_version=1.0-SNAPSHOT
maven_group=org.CobbleUtils
archives_base_name=CobbleRogueLike
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.116.17+1.21.1
fabric_kotlin_version=1.13.4+kotlin.2.2.0
# check this on https://maven.impactdev.net/#browse/browse:cobblemon-releases
cobblemon_version=1.6.1+1.21.1
